  version: "3.9"
  services:
    gestion-station-ski:
      image: devopsprojectback
      container_name: devopsprojectback
      ports:
        - "8083:8083"
      restart: always
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/devops?autoReconnect=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD:
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      depends_on:
        - mysql-container
      networks:
        - spring-network

    mysql-container:
      image: "mysql:5.6"
      container_name: mysql-container
      environment:
        MYSQL_ROOT_PASSWORD: root
        #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: devops
      ports:
        - "3306:3306"
      restart: unless-stopped
      networks:
        - spring-network


  networks:
    spring-network:



